name: builder

on:
  push:
    paths-ignore:
      - 'README.md'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore 
    
    - name: Build
      run: dotnet build "GameSnake/MonoGameSnake.csproj" --no-restore

    - name: Test
      run: dotnet test "TestSnake/TestSnake.csproj" --no-restore --verbosity normal
